sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
install:
  - pip install coverage coveralls flake8 nose pep8-naming wheel
  - pip wheel .
  - pip install --find-links=$PWD/wheelhouse honcho[export]
script:
  - nosetests --with-coverage --cover-branches --cover-package honcho honcho/test/unit
  - nosetests honcho/test/integration
  - flake8 honcho
after_success:
  - coveralls
