# http://travis-ci.org/#!/nickstenning/honcho/
# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - 2.7
  - pypy
install:
  - python setup.py install
script: python setup.py test
