sudo: false
language: python
matrix:
  include:
    - python: "2.6"
      env: TOXENV=py26
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "pypy"
      env: TOXENV=pypy
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=docs
install:
  - pip install tox
script:
  - tox
after_success:
  - tox -e coverage
  - tox -e codecov
