language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -r requirements_dev.txt
  - pip install 'coverage<3.999.999' flake8 nose pep8-naming
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-branches --cover-package honcho honcho/test/unit
  - nosetests honcho/test/integration
  - flake8 honcho
after_success:
  - coveralls
