#!/usr/bin/env python
import os
import sys

HERE = os.path.dirname(__file__)
ROOT = os.path.join(HERE, '..')

sys.path.insert(0, ROOT)

def main():
    os.chdir(ROOT)

    from honcho import __version__

    vt = map(int, __version__.split('.'))
    vt[-1] += 1

    bumped = '.'.join(map(str, vt))

    with open('honcho/__init__.py') as fp:
        content = fp.read()

    content = content.replace("__version__ = '%s'" % __version__,
                              "__version__ = '%s'" % bumped)

    with open('honcho/__init__.py', 'w') as fp:
        fp.write(content)

if __name__ == '__main__':
    main()

